version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - ZsgsDesign
  assignees:
  - ZsgsDesign
  labels:
  - Vulnerability
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 6.20.15
    - 6.20.16
    - 6.20.17
    - 6.20.18
    - 6.20.23
    - 6.20.24
  - dependency-name: npm-asset/codemirror
    versions:
    - 5.59.2
    - 5.59.3
    - 5.60.0
  - dependency-name: njuptaaa/moss
    versions:
    - 1.4.0
  - dependency-name: maatwebsite/excel
    versions:
    - 3.1.27
    - 3.1.28
  - dependency-name: npm-asset/lodash
    versions:
    - 4.17.21-patch1
  - dependency-name: filp/whoops
    versions:
    - 2.9.2
  - dependency-name: phpoffice/phpspreadsheet
    versions:
    - 1.16.0
