version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: beta
  reviewers:
  - lvdat
  assignees:
  - lvdat
  labels:
  - dependencies
  - php
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: beta
  reviewers:
  - lvdat
  assignees:
  - lvdat
  labels:
  - dependencies
  - javascript
  versioning-strategy: lockfile-only
